[build]
target = "Trunk.html"
dist = "public/wasm"
public_url = "/wasm/"
pattern_script = """
<script type="module">
  import init, * as exports from '{base}{js}';
  init('{base}{wasm}').then(wasm=> {
     onWasmInstantiated(wasm, exports);
  });
</script>
"""

[watch]
watch = ["src"]
