[build]
target = "public/Trunk.html"
dist = "dist"
pattern_script = """
<script type="module">
  import init, * as exports from '{base}{js}';
  init('{base}{wasm}').then(wasm=> {
     onWasmInstantiated(wasm, exports);
  });
</script>
"""

[watch]
watch = ["src","public"]
ignore= ["dist", "node_modules"]
