[build]
target = "Trunk.html"
dist = "target/trunk"
pattern_script = """
<script type="module">
  import init, * as exports from '{base}{js}';
  init('{base}{wasm}').then(wasm=> {
     onWasmInstantiated(wasm, exports);
  });
</script>
"""

[watch]
watch = ["Trunk.html", "Cargo.toml", "src"]
